update

diff --git a/.github/workflows/chik-test.yml b/.github/workflows/chik-test.yml
--- a/.github/workflows/chik-test.yml
+++ b/.github/workflows/chik-test.yml
@@ -21,4 +21,22 @@ jobs:
             });
             return release.data.tag_name;
 
-      - run: docker build --build-arg BRANCH="${{ steps.tag.outputs.result }}" .
+      - run: docker build --build-arg BRANCH="${{ steps.tag.outputs.result }}" -t localtest:latest .
+
+      - run: docker run -d --name=chik localtest:latest
+
+      - timeout-minutes: 10
+        run: |
+          while true; do
+            HEALTH_STATUS=$(docker inspect --format="{{.State.Health.Status}}" chik)
+            if [ "$HEALTH_STATUS" == "starting" ]; then
+              echo "Container chik is still starting. Waiting..."
+              sleep 1
+            elif [ "$HEALTH_STATUS" == "healthy" ]; then
+              echo "Health check succeeded for container chik"
+              break
+            else
+              echo "Health check failed for container chik"
+              exit 1
+            fi
+          done
